// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IntelliTrustCredentials IntelliTrust™ IDP specific credentials
//
// swagger:model IntelliTrustCredentials
type IntelliTrustCredentials struct {

	// OAuth client application secret from your Entrust Datacard® IntelliTrust™ Authentication
	// Service general settings
	ClientSecret string `json:"client_secret,omitempty" yaml:"client_secret,omitempty"`
}

// Validate validates this intelli trust credentials
func (m *IntelliTrustCredentials) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this intelli trust credentials based on context it is used
func (m *IntelliTrustCredentials) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IntelliTrustCredentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IntelliTrustCredentials) UnmarshalBinary(b []byte) error {
	var res IntelliTrustCredentials
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
