// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/client/apis"
	"github.com/cloudentity/acp-client-go/client/claims"
	"github.com/cloudentity/acp-client-go/client/clients"
	"github.com/cloudentity/acp-client-go/client/consents"
	"github.com/cloudentity/acp-client-go/client/environment"
	"github.com/cloudentity/acp-client-go/client/gateways"
	"github.com/cloudentity/acp-client-go/client/idps"
	"github.com/cloudentity/acp-client-go/client/keys"
	"github.com/cloudentity/acp-client-go/client/logins"
	"github.com/cloudentity/acp-client-go/client/mfa_methods"
	"github.com/cloudentity/acp-client-go/client/oauth2"
	"github.com/cloudentity/acp-client-go/client/openbanking_b_r"
	"github.com/cloudentity/acp-client-go/client/openbanking_common"
	"github.com/cloudentity/acp-client-go/client/openbanking_u_k"
	"github.com/cloudentity/acp-client-go/client/policies"
	"github.com/cloudentity/acp-client-go/client/recent_activities"
	"github.com/cloudentity/acp-client-go/client/scopes"
	"github.com/cloudentity/acp-client-go/client/scripts"
	"github.com/cloudentity/acp-client-go/client/secrets"
	"github.com/cloudentity/acp-client-go/client/servers"
	"github.com/cloudentity/acp-client-go/client/services"
	"github.com/cloudentity/acp-client-go/client/stats"
	"github.com/cloudentity/acp-client-go/client/system"
	"github.com/cloudentity/acp-client-go/client/tenants"
	"github.com/cloudentity/acp-client-go/client/web"
)

// Default acp HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost:8443"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new acp HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Acp {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new acp HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Acp {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new acp client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Acp {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Acp)
	cli.Transport = transport
	cli.Apis = apis.New(transport, formats)
	cli.Claims = claims.New(transport, formats)
	cli.Clients = clients.New(transport, formats)
	cli.Consents = consents.New(transport, formats)
	cli.Environment = environment.New(transport, formats)
	cli.Gateways = gateways.New(transport, formats)
	cli.Idps = idps.New(transport, formats)
	cli.Keys = keys.New(transport, formats)
	cli.Logins = logins.New(transport, formats)
	cli.MfaMethods = mfa_methods.New(transport, formats)
	cli.Oauth2 = oauth2.New(transport, formats)
	cli.Openbankingbr = openbanking_b_r.New(transport, formats)
	cli.OpenbankingCommon = openbanking_common.New(transport, formats)
	cli.Openbankinguk = openbanking_u_k.New(transport, formats)
	cli.Policies = policies.New(transport, formats)
	cli.RecentActivities = recent_activities.New(transport, formats)
	cli.Scopes = scopes.New(transport, formats)
	cli.Scripts = scripts.New(transport, formats)
	cli.Secrets = secrets.New(transport, formats)
	cli.Servers = servers.New(transport, formats)
	cli.Services = services.New(transport, formats)
	cli.Stats = stats.New(transport, formats)
	cli.System = system.New(transport, formats)
	cli.Tenants = tenants.New(transport, formats)
	cli.Web = web.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Acp is a client for acp
type Acp struct {
	Apis apis.ClientService

	Claims claims.ClientService

	Clients clients.ClientService

	Consents consents.ClientService

	Environment environment.ClientService

	Gateways gateways.ClientService

	Idps idps.ClientService

	Keys keys.ClientService

	Logins logins.ClientService

	MfaMethods mfa_methods.ClientService

	Oauth2 oauth2.ClientService

	Openbankingbr openbanking_b_r.ClientService

	OpenbankingCommon openbanking_common.ClientService

	Openbankinguk openbanking_u_k.ClientService

	Policies policies.ClientService

	RecentActivities recent_activities.ClientService

	Scopes scopes.ClientService

	Scripts scripts.ClientService

	Secrets secrets.ClientService

	Servers servers.ClientService

	Services services.ClientService

	Stats stats.ClientService

	System system.ClientService

	Tenants tenants.ClientService

	Web web.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Acp) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Apis.SetTransport(transport)
	c.Claims.SetTransport(transport)
	c.Clients.SetTransport(transport)
	c.Consents.SetTransport(transport)
	c.Environment.SetTransport(transport)
	c.Gateways.SetTransport(transport)
	c.Idps.SetTransport(transport)
	c.Keys.SetTransport(transport)
	c.Logins.SetTransport(transport)
	c.MfaMethods.SetTransport(transport)
	c.Oauth2.SetTransport(transport)
	c.Openbankingbr.SetTransport(transport)
	c.OpenbankingCommon.SetTransport(transport)
	c.Openbankinguk.SetTransport(transport)
	c.Policies.SetTransport(transport)
	c.RecentActivities.SetTransport(transport)
	c.Scopes.SetTransport(transport)
	c.Scripts.SetTransport(transport)
	c.Secrets.SetTransport(transport)
	c.Servers.SetTransport(transport)
	c.Services.SetTransport(transport)
	c.Stats.SetTransport(transport)
	c.System.SetTransport(transport)
	c.Tenants.SetTransport(transport)
	c.Web.SetTransport(transport)
}
