// Code generated by go-swagger; DO NOT EDIT.

package openbanking_b_r

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteDataAccessConsentDeprecatedParams creates a new DeleteDataAccessConsentDeprecatedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteDataAccessConsentDeprecatedParams() *DeleteDataAccessConsentDeprecatedParams {
	return &DeleteDataAccessConsentDeprecatedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDataAccessConsentDeprecatedParamsWithTimeout creates a new DeleteDataAccessConsentDeprecatedParams object
// with the ability to set a timeout on a request.
func NewDeleteDataAccessConsentDeprecatedParamsWithTimeout(timeout time.Duration) *DeleteDataAccessConsentDeprecatedParams {
	return &DeleteDataAccessConsentDeprecatedParams{
		timeout: timeout,
	}
}

// NewDeleteDataAccessConsentDeprecatedParamsWithContext creates a new DeleteDataAccessConsentDeprecatedParams object
// with the ability to set a context for a request.
func NewDeleteDataAccessConsentDeprecatedParamsWithContext(ctx context.Context) *DeleteDataAccessConsentDeprecatedParams {
	return &DeleteDataAccessConsentDeprecatedParams{
		Context: ctx,
	}
}

// NewDeleteDataAccessConsentDeprecatedParamsWithHTTPClient creates a new DeleteDataAccessConsentDeprecatedParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteDataAccessConsentDeprecatedParamsWithHTTPClient(client *http.Client) *DeleteDataAccessConsentDeprecatedParams {
	return &DeleteDataAccessConsentDeprecatedParams{
		HTTPClient: client,
	}
}

/* DeleteDataAccessConsentDeprecatedParams contains all the parameters to send to the API endpoint
   for the delete data access consent deprecated operation.

   Typically these are written to a http.Request.
*/
type DeleteDataAccessConsentDeprecatedParams struct {

	/* ConsentID.

	   Consent id

	   Format: consentID
	*/
	ConsentID string

	/* XCustomerUserAgent.

	     The header indicates the user-agent that the PSU is using.

	The TPP may populate this field with the user-agent indicated by the PSU.
	If the PSU is using a TPP mobile app, the TPP must ensure that the user-agent string
	is different from browser based user-agent strings.
	*/
	XCustomerUserAgent *string

	/* XFapiAuthDate.

	     The time when the PSU last logged in with the TPP.

	The value is supplied as a HTTP-date as in section 7.1.1.1 of [RFC7231]
	*/
	XFapiAuthDate *string

	/* XFapiCustomerIPAddress.

	   The PSU's IP address if the PSU is currently logged in with the TPP.
	*/
	XFapiCustomerIPAddress *string

	/* XFapiInteractionID.

	     An RFC4122 UID used as a correlation Id.

	If provided, the ASPSP must "play back" this value
	in the x-fapi-interaction-id response header.
	*/
	XFapiInteractionID *string

	/* XJwsSignature.

	     Header containing a detached JWS signature of the body of the payload.

	Refer to resource specific documentation on when this header must be specified.
	*/
	XJwsSignature *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete data access consent deprecated params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDataAccessConsentDeprecatedParams) WithDefaults() *DeleteDataAccessConsentDeprecatedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete data access consent deprecated params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDataAccessConsentDeprecatedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) WithTimeout(timeout time.Duration) *DeleteDataAccessConsentDeprecatedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) WithContext(ctx context.Context) *DeleteDataAccessConsentDeprecatedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) WithHTTPClient(client *http.Client) *DeleteDataAccessConsentDeprecatedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConsentID adds the consentID to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) WithConsentID(consentID string) *DeleteDataAccessConsentDeprecatedParams {
	o.SetConsentID(consentID)
	return o
}

// SetConsentID adds the consentId to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) SetConsentID(consentID string) {
	o.ConsentID = consentID
}

// WithXCustomerUserAgent adds the xCustomerUserAgent to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) WithXCustomerUserAgent(xCustomerUserAgent *string) *DeleteDataAccessConsentDeprecatedParams {
	o.SetXCustomerUserAgent(xCustomerUserAgent)
	return o
}

// SetXCustomerUserAgent adds the xCustomerUserAgent to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) SetXCustomerUserAgent(xCustomerUserAgent *string) {
	o.XCustomerUserAgent = xCustomerUserAgent
}

// WithXFapiAuthDate adds the xFapiAuthDate to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) WithXFapiAuthDate(xFapiAuthDate *string) *DeleteDataAccessConsentDeprecatedParams {
	o.SetXFapiAuthDate(xFapiAuthDate)
	return o
}

// SetXFapiAuthDate adds the xFapiAuthDate to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) SetXFapiAuthDate(xFapiAuthDate *string) {
	o.XFapiAuthDate = xFapiAuthDate
}

// WithXFapiCustomerIPAddress adds the xFapiCustomerIPAddress to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) WithXFapiCustomerIPAddress(xFapiCustomerIPAddress *string) *DeleteDataAccessConsentDeprecatedParams {
	o.SetXFapiCustomerIPAddress(xFapiCustomerIPAddress)
	return o
}

// SetXFapiCustomerIPAddress adds the xFapiCustomerIpAddress to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) SetXFapiCustomerIPAddress(xFapiCustomerIPAddress *string) {
	o.XFapiCustomerIPAddress = xFapiCustomerIPAddress
}

// WithXFapiInteractionID adds the xFapiInteractionID to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) WithXFapiInteractionID(xFapiInteractionID *string) *DeleteDataAccessConsentDeprecatedParams {
	o.SetXFapiInteractionID(xFapiInteractionID)
	return o
}

// SetXFapiInteractionID adds the xFapiInteractionId to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) SetXFapiInteractionID(xFapiInteractionID *string) {
	o.XFapiInteractionID = xFapiInteractionID
}

// WithXJwsSignature adds the xJwsSignature to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) WithXJwsSignature(xJwsSignature *string) *DeleteDataAccessConsentDeprecatedParams {
	o.SetXJwsSignature(xJwsSignature)
	return o
}

// SetXJwsSignature adds the xJwsSignature to the delete data access consent deprecated params
func (o *DeleteDataAccessConsentDeprecatedParams) SetXJwsSignature(xJwsSignature *string) {
	o.XJwsSignature = xJwsSignature
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDataAccessConsentDeprecatedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param consentID
	if err := r.SetPathParam("consentID", o.ConsentID); err != nil {
		return err
	}

	if o.XCustomerUserAgent != nil {

		// header param x-customer-user-agent
		if err := r.SetHeaderParam("x-customer-user-agent", *o.XCustomerUserAgent); err != nil {
			return err
		}
	}

	if o.XFapiAuthDate != nil {

		// header param x-fapi-auth-date
		if err := r.SetHeaderParam("x-fapi-auth-date", *o.XFapiAuthDate); err != nil {
			return err
		}
	}

	if o.XFapiCustomerIPAddress != nil {

		// header param x-fapi-customer-ip-address
		if err := r.SetHeaderParam("x-fapi-customer-ip-address", *o.XFapiCustomerIPAddress); err != nil {
			return err
		}
	}

	if o.XFapiInteractionID != nil {

		// header param x-fapi-interaction-id
		if err := r.SetHeaderParam("x-fapi-interaction-id", *o.XFapiInteractionID); err != nil {
			return err
		}
	}

	if o.XJwsSignature != nil {

		// header param x-jws-signature
		if err := r.SetHeaderParam("x-jws-signature", *o.XJwsSignature); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
