// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/identitysystem/models"
)

// ImportTenantConfigurationReader is a Reader for the ImportTenantConfiguration structure.
type ImportTenantConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImportTenantConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewImportTenantConfigurationNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewImportTenantConfigurationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewImportTenantConfigurationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewImportTenantConfigurationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewImportTenantConfigurationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewImportTenantConfigurationConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewImportTenantConfigurationUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewImportTenantConfigurationTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewImportTenantConfigurationNoContent creates a ImportTenantConfigurationNoContent with default headers values
func NewImportTenantConfigurationNoContent() *ImportTenantConfigurationNoContent {
	return &ImportTenantConfigurationNoContent{}
}

/*
ImportTenantConfigurationNoContent describes a response with status code 204, with default header values.

	configuration has been imported
*/
type ImportTenantConfigurationNoContent struct {
}

// IsSuccess returns true when this import tenant configuration no content response has a 2xx status code
func (o *ImportTenantConfigurationNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this import tenant configuration no content response has a 3xx status code
func (o *ImportTenantConfigurationNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this import tenant configuration no content response has a 4xx status code
func (o *ImportTenantConfigurationNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this import tenant configuration no content response has a 5xx status code
func (o *ImportTenantConfigurationNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this import tenant configuration no content response a status code equal to that given
func (o *ImportTenantConfigurationNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *ImportTenantConfigurationNoContent) Error() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationNoContent ", 204)
}

func (o *ImportTenantConfigurationNoContent) String() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationNoContent ", 204)
}

func (o *ImportTenantConfigurationNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewImportTenantConfigurationBadRequest creates a ImportTenantConfigurationBadRequest with default headers values
func NewImportTenantConfigurationBadRequest() *ImportTenantConfigurationBadRequest {
	return &ImportTenantConfigurationBadRequest{}
}

/*
ImportTenantConfigurationBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type ImportTenantConfigurationBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this import tenant configuration bad request response has a 2xx status code
func (o *ImportTenantConfigurationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this import tenant configuration bad request response has a 3xx status code
func (o *ImportTenantConfigurationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this import tenant configuration bad request response has a 4xx status code
func (o *ImportTenantConfigurationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this import tenant configuration bad request response has a 5xx status code
func (o *ImportTenantConfigurationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this import tenant configuration bad request response a status code equal to that given
func (o *ImportTenantConfigurationBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ImportTenantConfigurationBadRequest) Error() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationBadRequest  %+v", 400, o.Payload)
}

func (o *ImportTenantConfigurationBadRequest) String() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationBadRequest  %+v", 400, o.Payload)
}

func (o *ImportTenantConfigurationBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ImportTenantConfigurationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImportTenantConfigurationUnauthorized creates a ImportTenantConfigurationUnauthorized with default headers values
func NewImportTenantConfigurationUnauthorized() *ImportTenantConfigurationUnauthorized {
	return &ImportTenantConfigurationUnauthorized{}
}

/*
ImportTenantConfigurationUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ImportTenantConfigurationUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this import tenant configuration unauthorized response has a 2xx status code
func (o *ImportTenantConfigurationUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this import tenant configuration unauthorized response has a 3xx status code
func (o *ImportTenantConfigurationUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this import tenant configuration unauthorized response has a 4xx status code
func (o *ImportTenantConfigurationUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this import tenant configuration unauthorized response has a 5xx status code
func (o *ImportTenantConfigurationUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this import tenant configuration unauthorized response a status code equal to that given
func (o *ImportTenantConfigurationUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *ImportTenantConfigurationUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationUnauthorized  %+v", 401, o.Payload)
}

func (o *ImportTenantConfigurationUnauthorized) String() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationUnauthorized  %+v", 401, o.Payload)
}

func (o *ImportTenantConfigurationUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *ImportTenantConfigurationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImportTenantConfigurationForbidden creates a ImportTenantConfigurationForbidden with default headers values
func NewImportTenantConfigurationForbidden() *ImportTenantConfigurationForbidden {
	return &ImportTenantConfigurationForbidden{}
}

/*
ImportTenantConfigurationForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ImportTenantConfigurationForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this import tenant configuration forbidden response has a 2xx status code
func (o *ImportTenantConfigurationForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this import tenant configuration forbidden response has a 3xx status code
func (o *ImportTenantConfigurationForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this import tenant configuration forbidden response has a 4xx status code
func (o *ImportTenantConfigurationForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this import tenant configuration forbidden response has a 5xx status code
func (o *ImportTenantConfigurationForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this import tenant configuration forbidden response a status code equal to that given
func (o *ImportTenantConfigurationForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *ImportTenantConfigurationForbidden) Error() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationForbidden  %+v", 403, o.Payload)
}

func (o *ImportTenantConfigurationForbidden) String() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationForbidden  %+v", 403, o.Payload)
}

func (o *ImportTenantConfigurationForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *ImportTenantConfigurationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImportTenantConfigurationNotFound creates a ImportTenantConfigurationNotFound with default headers values
func NewImportTenantConfigurationNotFound() *ImportTenantConfigurationNotFound {
	return &ImportTenantConfigurationNotFound{}
}

/*
ImportTenantConfigurationNotFound describes a response with status code 404, with default header values.

Not found
*/
type ImportTenantConfigurationNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this import tenant configuration not found response has a 2xx status code
func (o *ImportTenantConfigurationNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this import tenant configuration not found response has a 3xx status code
func (o *ImportTenantConfigurationNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this import tenant configuration not found response has a 4xx status code
func (o *ImportTenantConfigurationNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this import tenant configuration not found response has a 5xx status code
func (o *ImportTenantConfigurationNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this import tenant configuration not found response a status code equal to that given
func (o *ImportTenantConfigurationNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *ImportTenantConfigurationNotFound) Error() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationNotFound  %+v", 404, o.Payload)
}

func (o *ImportTenantConfigurationNotFound) String() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationNotFound  %+v", 404, o.Payload)
}

func (o *ImportTenantConfigurationNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *ImportTenantConfigurationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImportTenantConfigurationConflict creates a ImportTenantConfigurationConflict with default headers values
func NewImportTenantConfigurationConflict() *ImportTenantConfigurationConflict {
	return &ImportTenantConfigurationConflict{}
}

/*
ImportTenantConfigurationConflict describes a response with status code 409, with default header values.

Conflict
*/
type ImportTenantConfigurationConflict struct {
	Payload *models.Error
}

// IsSuccess returns true when this import tenant configuration conflict response has a 2xx status code
func (o *ImportTenantConfigurationConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this import tenant configuration conflict response has a 3xx status code
func (o *ImportTenantConfigurationConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this import tenant configuration conflict response has a 4xx status code
func (o *ImportTenantConfigurationConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this import tenant configuration conflict response has a 5xx status code
func (o *ImportTenantConfigurationConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this import tenant configuration conflict response a status code equal to that given
func (o *ImportTenantConfigurationConflict) IsCode(code int) bool {
	return code == 409
}

func (o *ImportTenantConfigurationConflict) Error() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationConflict  %+v", 409, o.Payload)
}

func (o *ImportTenantConfigurationConflict) String() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationConflict  %+v", 409, o.Payload)
}

func (o *ImportTenantConfigurationConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *ImportTenantConfigurationConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImportTenantConfigurationUnprocessableEntity creates a ImportTenantConfigurationUnprocessableEntity with default headers values
func NewImportTenantConfigurationUnprocessableEntity() *ImportTenantConfigurationUnprocessableEntity {
	return &ImportTenantConfigurationUnprocessableEntity{}
}

/*
ImportTenantConfigurationUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable entity
*/
type ImportTenantConfigurationUnprocessableEntity struct {
	Payload *models.Error
}

// IsSuccess returns true when this import tenant configuration unprocessable entity response has a 2xx status code
func (o *ImportTenantConfigurationUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this import tenant configuration unprocessable entity response has a 3xx status code
func (o *ImportTenantConfigurationUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this import tenant configuration unprocessable entity response has a 4xx status code
func (o *ImportTenantConfigurationUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this import tenant configuration unprocessable entity response has a 5xx status code
func (o *ImportTenantConfigurationUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this import tenant configuration unprocessable entity response a status code equal to that given
func (o *ImportTenantConfigurationUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

func (o *ImportTenantConfigurationUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *ImportTenantConfigurationUnprocessableEntity) String() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *ImportTenantConfigurationUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *ImportTenantConfigurationUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImportTenantConfigurationTooManyRequests creates a ImportTenantConfigurationTooManyRequests with default headers values
func NewImportTenantConfigurationTooManyRequests() *ImportTenantConfigurationTooManyRequests {
	return &ImportTenantConfigurationTooManyRequests{}
}

/*
ImportTenantConfigurationTooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type ImportTenantConfigurationTooManyRequests struct {
	Payload *models.Error
}

// IsSuccess returns true when this import tenant configuration too many requests response has a 2xx status code
func (o *ImportTenantConfigurationTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this import tenant configuration too many requests response has a 3xx status code
func (o *ImportTenantConfigurationTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this import tenant configuration too many requests response has a 4xx status code
func (o *ImportTenantConfigurationTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this import tenant configuration too many requests response has a 5xx status code
func (o *ImportTenantConfigurationTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this import tenant configuration too many requests response a status code equal to that given
func (o *ImportTenantConfigurationTooManyRequests) IsCode(code int) bool {
	return code == 429
}

func (o *ImportTenantConfigurationTooManyRequests) Error() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationTooManyRequests  %+v", 429, o.Payload)
}

func (o *ImportTenantConfigurationTooManyRequests) String() string {
	return fmt.Sprintf("[PUT /configuration][%d] importTenantConfigurationTooManyRequests  %+v", 429, o.Payload)
}

func (o *ImportTenantConfigurationTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *ImportTenantConfigurationTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
