// Code generated by go-swagger; DO NOT EDIT.

package keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/admin/models"
)

// NewSetAutomaticKeyRotationParams creates a new SetAutomaticKeyRotationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetAutomaticKeyRotationParams() *SetAutomaticKeyRotationParams {
	return &SetAutomaticKeyRotationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetAutomaticKeyRotationParamsWithTimeout creates a new SetAutomaticKeyRotationParams object
// with the ability to set a timeout on a request.
func NewSetAutomaticKeyRotationParamsWithTimeout(timeout time.Duration) *SetAutomaticKeyRotationParams {
	return &SetAutomaticKeyRotationParams{
		timeout: timeout,
	}
}

// NewSetAutomaticKeyRotationParamsWithContext creates a new SetAutomaticKeyRotationParams object
// with the ability to set a context for a request.
func NewSetAutomaticKeyRotationParamsWithContext(ctx context.Context) *SetAutomaticKeyRotationParams {
	return &SetAutomaticKeyRotationParams{
		Context: ctx,
	}
}

// NewSetAutomaticKeyRotationParamsWithHTTPClient creates a new SetAutomaticKeyRotationParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetAutomaticKeyRotationParamsWithHTTPClient(client *http.Client) *SetAutomaticKeyRotationParams {
	return &SetAutomaticKeyRotationParams{
		HTTPClient: client,
	}
}

/*
SetAutomaticKeyRotationParams contains all the parameters to send to the API endpoint

	for the set automatic key rotation operation.

	Typically these are written to a http.Request.
*/
type SetAutomaticKeyRotationParams struct {

	/* AutomaticKeyRotation.

	   Automatic key rotation configuration
	*/
	AutomaticKeyRotation *models.AutomaticKeyRotation

	/* Use.

	   Key use (sig or enc)

	   Default: "sig"
	*/
	Use *string

	/* Wid.

	   Authorization server id

	   Default: "default"
	*/
	Wid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set automatic key rotation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetAutomaticKeyRotationParams) WithDefaults() *SetAutomaticKeyRotationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set automatic key rotation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetAutomaticKeyRotationParams) SetDefaults() {
	var (
		useDefault = string("sig")

		widDefault = string("default")
	)

	val := SetAutomaticKeyRotationParams{
		Use: &useDefault,
		Wid: widDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the set automatic key rotation params
func (o *SetAutomaticKeyRotationParams) WithTimeout(timeout time.Duration) *SetAutomaticKeyRotationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set automatic key rotation params
func (o *SetAutomaticKeyRotationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set automatic key rotation params
func (o *SetAutomaticKeyRotationParams) WithContext(ctx context.Context) *SetAutomaticKeyRotationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set automatic key rotation params
func (o *SetAutomaticKeyRotationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set automatic key rotation params
func (o *SetAutomaticKeyRotationParams) WithHTTPClient(client *http.Client) *SetAutomaticKeyRotationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set automatic key rotation params
func (o *SetAutomaticKeyRotationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAutomaticKeyRotation adds the automaticKeyRotation to the set automatic key rotation params
func (o *SetAutomaticKeyRotationParams) WithAutomaticKeyRotation(automaticKeyRotation *models.AutomaticKeyRotation) *SetAutomaticKeyRotationParams {
	o.SetAutomaticKeyRotation(automaticKeyRotation)
	return o
}

// SetAutomaticKeyRotation adds the automaticKeyRotation to the set automatic key rotation params
func (o *SetAutomaticKeyRotationParams) SetAutomaticKeyRotation(automaticKeyRotation *models.AutomaticKeyRotation) {
	o.AutomaticKeyRotation = automaticKeyRotation
}

// WithUse adds the use to the set automatic key rotation params
func (o *SetAutomaticKeyRotationParams) WithUse(use *string) *SetAutomaticKeyRotationParams {
	o.SetUse(use)
	return o
}

// SetUse adds the use to the set automatic key rotation params
func (o *SetAutomaticKeyRotationParams) SetUse(use *string) {
	o.Use = use
}

// WithWid adds the wid to the set automatic key rotation params
func (o *SetAutomaticKeyRotationParams) WithWid(wid string) *SetAutomaticKeyRotationParams {
	o.SetWid(wid)
	return o
}

// SetWid adds the wid to the set automatic key rotation params
func (o *SetAutomaticKeyRotationParams) SetWid(wid string) {
	o.Wid = wid
}

// WriteToRequest writes these params to a swagger request
func (o *SetAutomaticKeyRotationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.AutomaticKeyRotation != nil {
		if err := r.SetBodyParam(o.AutomaticKeyRotation); err != nil {
			return err
		}
	}

	if o.Use != nil {

		// query param use
		var qrUse string

		if o.Use != nil {
			qrUse = *o.Use
		}
		qUse := qrUse
		if qUse != "" {

			if err := r.SetQueryParam("use", qUse); err != nil {
				return err
			}
		}
	}

	// path param wid
	if err := r.SetPathParam("wid", o.Wid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
