// Code generated by go-swagger; DO NOT EDIT.

package a_c_rs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/admin/models"
)

// NewCreateACRParams creates a new CreateACRParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateACRParams() *CreateACRParams {
	return &CreateACRParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateACRParamsWithTimeout creates a new CreateACRParams object
// with the ability to set a timeout on a request.
func NewCreateACRParamsWithTimeout(timeout time.Duration) *CreateACRParams {
	return &CreateACRParams{
		timeout: timeout,
	}
}

// NewCreateACRParamsWithContext creates a new CreateACRParams object
// with the ability to set a context for a request.
func NewCreateACRParamsWithContext(ctx context.Context) *CreateACRParams {
	return &CreateACRParams{
		Context: ctx,
	}
}

// NewCreateACRParamsWithHTTPClient creates a new CreateACRParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateACRParamsWithHTTPClient(client *http.Client) *CreateACRParams {
	return &CreateACRParams{
		HTTPClient: client,
	}
}

/*
CreateACRParams contains all the parameters to send to the API endpoint

	for the create a c r operation.

	Typically these are written to a http.Request.
*/
type CreateACRParams struct {

	// ACR.
	ACR *models.ACR

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	/* Wid.

	   Authorization server id

	   Default: "default"
	*/
	Wid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create a c r params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateACRParams) WithDefaults() *CreateACRParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create a c r params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateACRParams) SetDefaults() {
	var (
		widDefault = string("default")
	)

	val := CreateACRParams{
		Wid: widDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the create a c r params
func (o *CreateACRParams) WithTimeout(timeout time.Duration) *CreateACRParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create a c r params
func (o *CreateACRParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create a c r params
func (o *CreateACRParams) WithContext(ctx context.Context) *CreateACRParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create a c r params
func (o *CreateACRParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create a c r params
func (o *CreateACRParams) WithHTTPClient(client *http.Client) *CreateACRParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create a c r params
func (o *CreateACRParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithACR adds the aCR to the create a c r params
func (o *CreateACRParams) WithACR(aCR *models.ACR) *CreateACRParams {
	o.SetACR(aCR)
	return o
}

// SetACR adds the aCR to the create a c r params
func (o *CreateACRParams) SetACR(aCR *models.ACR) {
	o.ACR = aCR
}

// WithIfMatch adds the ifMatch to the create a c r params
func (o *CreateACRParams) WithIfMatch(ifMatch *string) *CreateACRParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the create a c r params
func (o *CreateACRParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithWid adds the wid to the create a c r params
func (o *CreateACRParams) WithWid(wid string) *CreateACRParams {
	o.SetWid(wid)
	return o
}

// SetWid adds the wid to the create a c r params
func (o *CreateACRParams) SetWid(wid string) {
	o.Wid = wid
}

// WriteToRequest writes these params to a swagger request
func (o *CreateACRParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.ACR != nil {
		if err := r.SetBodyParam(o.ACR); err != nil {
			return err
		}
	}

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	// path param wid
	if err := r.SetPathParam("wid", o.Wid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
