// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/admin/models"
)

// NewSetPolicyExecutionPointsParams creates a new SetPolicyExecutionPointsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetPolicyExecutionPointsParams() *SetPolicyExecutionPointsParams {
	return &SetPolicyExecutionPointsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetPolicyExecutionPointsParamsWithTimeout creates a new SetPolicyExecutionPointsParams object
// with the ability to set a timeout on a request.
func NewSetPolicyExecutionPointsParamsWithTimeout(timeout time.Duration) *SetPolicyExecutionPointsParams {
	return &SetPolicyExecutionPointsParams{
		timeout: timeout,
	}
}

// NewSetPolicyExecutionPointsParamsWithContext creates a new SetPolicyExecutionPointsParams object
// with the ability to set a context for a request.
func NewSetPolicyExecutionPointsParamsWithContext(ctx context.Context) *SetPolicyExecutionPointsParams {
	return &SetPolicyExecutionPointsParams{
		Context: ctx,
	}
}

// NewSetPolicyExecutionPointsParamsWithHTTPClient creates a new SetPolicyExecutionPointsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetPolicyExecutionPointsParamsWithHTTPClient(client *http.Client) *SetPolicyExecutionPointsParams {
	return &SetPolicyExecutionPointsParams{
		HTTPClient: client,
	}
}

/*
SetPolicyExecutionPointsParams contains all the parameters to send to the API endpoint

	for the set policy execution points operation.

	Typically these are written to a http.Request.
*/
type SetPolicyExecutionPointsParams struct {

	// Executions.
	Executions *models.PolicyExecutionPoints

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	/* Wid.

	   Authorization server id

	   Default: "default"
	*/
	Wid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set policy execution points params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetPolicyExecutionPointsParams) WithDefaults() *SetPolicyExecutionPointsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set policy execution points params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetPolicyExecutionPointsParams) SetDefaults() {
	var (
		widDefault = string("default")
	)

	val := SetPolicyExecutionPointsParams{
		Wid: widDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the set policy execution points params
func (o *SetPolicyExecutionPointsParams) WithTimeout(timeout time.Duration) *SetPolicyExecutionPointsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set policy execution points params
func (o *SetPolicyExecutionPointsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set policy execution points params
func (o *SetPolicyExecutionPointsParams) WithContext(ctx context.Context) *SetPolicyExecutionPointsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set policy execution points params
func (o *SetPolicyExecutionPointsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set policy execution points params
func (o *SetPolicyExecutionPointsParams) WithHTTPClient(client *http.Client) *SetPolicyExecutionPointsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set policy execution points params
func (o *SetPolicyExecutionPointsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExecutions adds the executions to the set policy execution points params
func (o *SetPolicyExecutionPointsParams) WithExecutions(executions *models.PolicyExecutionPoints) *SetPolicyExecutionPointsParams {
	o.SetExecutions(executions)
	return o
}

// SetExecutions adds the executions to the set policy execution points params
func (o *SetPolicyExecutionPointsParams) SetExecutions(executions *models.PolicyExecutionPoints) {
	o.Executions = executions
}

// WithIfMatch adds the ifMatch to the set policy execution points params
func (o *SetPolicyExecutionPointsParams) WithIfMatch(ifMatch *string) *SetPolicyExecutionPointsParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the set policy execution points params
func (o *SetPolicyExecutionPointsParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithWid adds the wid to the set policy execution points params
func (o *SetPolicyExecutionPointsParams) WithWid(wid string) *SetPolicyExecutionPointsParams {
	o.SetWid(wid)
	return o
}

// SetWid adds the wid to the set policy execution points params
func (o *SetPolicyExecutionPointsParams) SetWid(wid string) {
	o.Wid = wid
}

// WriteToRequest writes these params to a swagger request
func (o *SetPolicyExecutionPointsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Executions != nil {
		if err := r.SetBodyParam(o.Executions); err != nil {
			return err
		}
	}

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	// path param wid
	if err := r.SetPathParam("wid", o.Wid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
