// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CDRConsentsRequest c d r consents request
//
// swagger:model CDRConsentsRequest
type CDRConsentsRequest struct {

	// List of accounts.
	//
	// It can refer to user bank accounts the client application is allowed to access.
	Accounts []string `json:"accounts" yaml:"accounts"`

	// A consent identifier.
	//
	// Use it to navigate through the request pagination when the number of consents is greater than
	// the `limit` set for results in the response.
	//
	// With `after_consent_id`, the list you obtain starts from the subsequent consent after the specified one. Also,
	// the response depends on the `sort` and `order` parameters, if any are passed.
	AfterConsentID string `json:"after_consent_id,omitempty" yaml:"after_consent_id,omitempty"`

	// A consent identifier.
	//
	// Use it to navigate through the request pagination when the number of consents is greater than
	// the limit set for results in the response.
	//
	// With `before_consent_id`, the list you obtain comprises consents up to the specified one. The specified consent
	// isn't included. Also, the response depends on the `sort` and `order` parameters, if any are passed.
	BeforeConsentID string `json:"before_consent_id,omitempty" yaml:"before_consent_id,omitempty"`

	// A client identifier.
	ClientID string `json:"client_id,omitempty" yaml:"client_id,omitempty"`

	// Customer identifier. It represents an organization. The customer identifier can cover several
	// user identifiers as organization members.
	//
	// When you pass a `customer_id` with your request, the response contains results related to the specified
	// organization, including the allowed information about its users and their arrangements.
	CustomerID string `json:"customer_id,omitempty" yaml:"customer_id,omitempty"`

	// Limit the number of results returned in the response.
	// Maximum: 100
	// Minimum: 1
	Limit int64 `json:"limit,omitempty" yaml:"limit,omitempty"`

	// Input: `acs` or `desc`.
	//
	// Set the order of results returned in the response.
	Order string `json:"order,omitempty" yaml:"order,omitempty"`

	// Sort results returned in the response.
	Sort string `json:"sort,omitempty" yaml:"sort,omitempty"`

	// List of the consent statuses.
	Status []string `json:"status" yaml:"status"`

	// Consent types.
	//
	// in:query
	Types []string `json:"types" yaml:"types"`

	// User identifier. It represents an end-user.
	//
	// When you pass a `user_id` with your request, the endpoint returns the details relating to the specified user.
	UserID string `json:"user_id,omitempty" yaml:"user_id,omitempty"`
}

// Validate validates this c d r consents request
func (m *CDRConsentsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLimit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CDRConsentsRequest) validateLimit(formats strfmt.Registry) error {
	if swag.IsZero(m.Limit) { // not required
		return nil
	}

	if err := validate.MinimumInt("limit", "body", m.Limit, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("limit", "body", m.Limit, 100, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this c d r consents request based on context it is used
func (m *CDRConsentsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CDRConsentsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CDRConsentsRequest) UnmarshalBinary(b []byte) error {
	var res CDRConsentsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
