// Code generated by go-swagger; DO NOT EDIT.

package apis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIParams creates a new GetAPIParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIParams() *GetAPIParams {
	return &GetAPIParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIParamsWithTimeout creates a new GetAPIParams object
// with the ability to set a timeout on a request.
func NewGetAPIParamsWithTimeout(timeout time.Duration) *GetAPIParams {
	return &GetAPIParams{
		timeout: timeout,
	}
}

// NewGetAPIParamsWithContext creates a new GetAPIParams object
// with the ability to set a context for a request.
func NewGetAPIParamsWithContext(ctx context.Context) *GetAPIParams {
	return &GetAPIParams{
		Context: ctx,
	}
}

// NewGetAPIParamsWithHTTPClient creates a new GetAPIParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIParamsWithHTTPClient(client *http.Client) *GetAPIParams {
	return &GetAPIParams{
		HTTPClient: client,
	}
}

/* GetAPIParams contains all the parameters to send to the API endpoint
   for the get API operation.

   Typically these are written to a http.Request.
*/
type GetAPIParams struct {

	// API.
	APIID string

	/* Tid.

	   Tenant id

	   Default: "default"
	*/
	Tid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIParams) WithDefaults() *GetAPIParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIParams) SetDefaults() {
	var (
		tidDefault = string("default")
	)

	val := GetAPIParams{
		Tid: tidDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get API params
func (o *GetAPIParams) WithTimeout(timeout time.Duration) *GetAPIParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API params
func (o *GetAPIParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API params
func (o *GetAPIParams) WithContext(ctx context.Context) *GetAPIParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API params
func (o *GetAPIParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API params
func (o *GetAPIParams) WithHTTPClient(client *http.Client) *GetAPIParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API params
func (o *GetAPIParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIID adds the api to the get API params
func (o *GetAPIParams) WithAPIID(api string) *GetAPIParams {
	o.SetAPIID(api)
	return o
}

// SetAPIID adds the api to the get API params
func (o *GetAPIParams) SetAPIID(api string) {
	o.APIID = api
}

// WithTid adds the tid to the get API params
func (o *GetAPIParams) WithTid(tid string) *GetAPIParams {
	o.SetTid(tid)
	return o
}

// SetTid adds the tid to the get API params
func (o *GetAPIParams) SetTid(tid string) {
	o.Tid = tid
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param api
	if err := r.SetPathParam("api", o.APIID); err != nil {
		return err
	}

	// path param tid
	if err := r.SetPathParam("tid", o.Tid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
