// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OktaSupervisorClient The `supervisor_client` parameter holds credentials for Okta's OAuth client application that are
// used to authorize to Okta to be able to create new client applications.
//
// swagger:model OktaSupervisorClient
type OktaSupervisorClient struct {

	// client id
	ClientID string `json:"client_id,omitempty" yaml:"client_id,omitempty"`

	// client private key
	PrivateKey string `json:"private_key,omitempty" yaml:"private_key,omitempty"`
}

// Validate validates this okta supervisor client
func (m *OktaSupervisorClient) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this okta supervisor client based on context it is used
func (m *OktaSupervisorClient) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OktaSupervisorClient) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OktaSupervisorClient) UnmarshalBinary(b []byte) error {
	var res OktaSupervisorClient
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
