// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// SpecVersion spec version
//
// swagger:model SpecVersion
type SpecVersion string

// Validate validates this spec version
func (m SpecVersion) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this spec version based on context it is used
func (m SpecVersion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
