// Code generated by go-swagger; DO NOT EDIT.

package schemas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cloudentity/acp-client-go/clients/identitysystem/models"
)

// NewSystemCreateSchemaParams creates a new SystemCreateSchemaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSystemCreateSchemaParams() *SystemCreateSchemaParams {
	return &SystemCreateSchemaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSystemCreateSchemaParamsWithTimeout creates a new SystemCreateSchemaParams object
// with the ability to set a timeout on a request.
func NewSystemCreateSchemaParamsWithTimeout(timeout time.Duration) *SystemCreateSchemaParams {
	return &SystemCreateSchemaParams{
		timeout: timeout,
	}
}

// NewSystemCreateSchemaParamsWithContext creates a new SystemCreateSchemaParams object
// with the ability to set a context for a request.
func NewSystemCreateSchemaParamsWithContext(ctx context.Context) *SystemCreateSchemaParams {
	return &SystemCreateSchemaParams{
		Context: ctx,
	}
}

// NewSystemCreateSchemaParamsWithHTTPClient creates a new SystemCreateSchemaParams object
// with the ability to set a custom HTTPClient for a request.
func NewSystemCreateSchemaParamsWithHTTPClient(client *http.Client) *SystemCreateSchemaParams {
	return &SystemCreateSchemaParams{
		HTTPClient: client,
	}
}

/*
SystemCreateSchemaParams contains all the parameters to send to the API endpoint

	for the system create schema operation.

	Typically these are written to a http.Request.
*/
type SystemCreateSchemaParams struct {

	// Schema.
	Schema *models.Schema

	/* IfMatch.

	   A server will only return requested resources if the resource matches one of the listed ETag value

	   Format: etag
	*/
	IfMatch *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the system create schema params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemCreateSchemaParams) WithDefaults() *SystemCreateSchemaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the system create schema params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SystemCreateSchemaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the system create schema params
func (o *SystemCreateSchemaParams) WithTimeout(timeout time.Duration) *SystemCreateSchemaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the system create schema params
func (o *SystemCreateSchemaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the system create schema params
func (o *SystemCreateSchemaParams) WithContext(ctx context.Context) *SystemCreateSchemaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the system create schema params
func (o *SystemCreateSchemaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the system create schema params
func (o *SystemCreateSchemaParams) WithHTTPClient(client *http.Client) *SystemCreateSchemaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the system create schema params
func (o *SystemCreateSchemaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSchema adds the schema to the system create schema params
func (o *SystemCreateSchemaParams) WithSchema(schema *models.Schema) *SystemCreateSchemaParams {
	o.SetSchema(schema)
	return o
}

// SetSchema adds the schema to the system create schema params
func (o *SystemCreateSchemaParams) SetSchema(schema *models.Schema) {
	o.Schema = schema
}

// WithIfMatch adds the ifMatch to the system create schema params
func (o *SystemCreateSchemaParams) WithIfMatch(ifMatch *string) *SystemCreateSchemaParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the system create schema params
func (o *SystemCreateSchemaParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WriteToRequest writes these params to a swagger request
func (o *SystemCreateSchemaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Schema != nil {
		if err := r.SetBodyParam(o.Schema); err != nil {
			return err
		}
	}

	if o.IfMatch != nil {

		// header param if-match
		if err := r.SetHeaderParam("if-match", *o.IfMatch); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
